### ISSUE TITLE
请问trojan协议不能限速吗？

### ISSUE THREAD

**Issue by lanhebe** [fregie/simple#8]
[试了好几个trojan节点，其中设定为512KB/s，都不能限速
![1](https://user-images.githubusercontent.com/5748516/134462967-ec9409b2-01ad-4cfb-9f3f-463bf1c09c58.png)
。

**Comment by lanhebe** [comment]
这边测试好几个ss节点，也是无法限速。请问功能如何开启？已在创建命令加入--limit 4 参数

**Comment by fregie** [comment]
可以的，我会尽快确认这个问题。

**Comment by lanhebe** [comment]
请问ss可以限速了吗？

**Comment by lanhebe** [comment]
请问限速问题解决了吗？看到请回复。非常关注此项目

**Comment by fregie** [comment]
> 请问限速问题解决了吗？看到请回复。非常关注此项目

最新版的trojan已经修复了上行限速的问题。引用最新版本trojan docker镜像即可。
https://github.com/fregie/trojan-go/releases/tag/v1.0.5
